load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "buildah_tool_lib",
    srcs = [
        "base_aware_source.go",
        "base_import.go",
        "bic_seed.go",
        "blob_coordinator.go",
        "buildah.go",
        "cache_push.go",
        "discard_destination.go",
        "flags.go",
        "image_export.go",
        "log.go",
        "main.go",
        "output.go",
        "prune.go",
    ],
    importpath = "github.com/bazel-contrib/rules_img/buildah/cmd/buildah_tool",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_containerd_stargz_snapshotter_estargz//:estargz",
        "@com_github_containerd_stargz_snapshotter_estargz//zstdchunked",
        "@com_github_klauspost_compress//zstd",
        "@com_github_opencontainers_go_digest//:go-digest",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@com_github_sirupsen_logrus//:logrus",
        "@com_github_spf13_cobra//:cobra",
        "@io_podman_go_buildah//:buildah",
        "@io_podman_go_buildah//define",
        "@io_podman_go_buildah//imagebuildah",
        "@io_podman_go_buildah//pkg/cli",
        "@io_podman_go_buildah//util",
        "@io_podman_go_common//libimage/manifests",
        "@io_podman_go_image_v5//copy",
        "@io_podman_go_image_v5//docker",
        "@io_podman_go_image_v5//docker/reference",
        "@io_podman_go_image_v5//pkg/blobcache",
        "@io_podman_go_image_v5//pkg/blobinfocache",
        "@io_podman_go_image_v5//pkg/blobinfocache/none",
        "@io_podman_go_image_v5//pkg/compression",
        "@io_podman_go_image_v5//signature",
        "@io_podman_go_image_v5//storage",
        "@io_podman_go_image_v5//transports",
        "@io_podman_go_image_v5//types",
        "@io_podman_go_storage//:storage",
        "@io_podman_go_storage//pkg/homedir",
        "@io_podman_go_storage//pkg/reexec",
        "@io_podman_go_storage//pkg/unshare",
    ],
)

go_binary(
    name = "buildah_tool",
    embed = [":buildah_tool_lib"],
    gotags = [
        "containers_image_openpgp",
        "exclude_graphdriver_btrfs",
    ],
    pure = "off",
    visibility = ["//visibility:public"],
)
