changelog:
  categories:
    - title: ⭐ Highlights
      labels:
        - highlight
    - title: What's Changed
      labels:
        - "*"
    - title: 🏗️ Dependencies
      labels:
        - dependencies
