load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tree",
    srcs = ["recorder.go"],
    importpath = "github.com/bazel-contrib/rules_img/img_tool/pkg/tree",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/api",
        "//pkg/fileopener",
        "//pkg/tree/runfiles",
        "//pkg/tree/treeartifact",
    ],
)

go_test(
    name = "tree_test",
    srcs = ["import_tar_test.go"],
    embed = [":tree"],
    deps = [
        "//pkg/api",
        "//pkg/compress",
        "//pkg/tarcas",
    ],
)
