"""Defines the provider that carries base image content between rules."""

DOC = """\
A description of container image content that is not (yet) a layer.

Rules that describe base image content -- users, CA certificates, a directory
skeleton, shared libraries -- return this provider instead of building a layer
of their own. The description propagates cheaply through dependencies, and the
`base_image_layer` rule finally merges every description it is given into a
single flat layer.
"""

FIELDS = dict(
    metadata = """\
Depset of File. Each file is one base metadata stream: a zstd-compressed
sequence of length-delimited protobuf messages, each describing one tar entry.

The format is an internal implementation detail of rules_img and may change
without notice; only the `img` tool reads it.
""",
    files = """\
Depset of File referenced by path from the metadata messages.

An entry whose content comes from a real file records that file's path, so the
file must be available to the action that builds the layer. Content generated by
the rule itself is stored inline in the metadata instead and contributes nothing
here.
""",
)

BaseImageContentInfo = provider(
    doc = DOC,
    fields = FIELDS,
)
