"""Mapping between Bazel constraint values and OCI platform fields.

`//img/private/config:target_os_cpu` reads the target platform through these tables, and the
routing repositories generated by the images module extension build their `config_setting`s from
them. Both sides have to agree: a generated routing branch for a constraint `target_os_cpu` does
not know about would select a manifest that `select_base` then refuses, and a constraint
`target_os_cpu` knows about but the router does not would make an image look incompatible. Keeping
one table is what makes that impossible.

Known gaps, inherited from `target_os_cpu` and deliberately not changed here: the variant
constraint values `//img/constraints/arm64:v8`, `:v8.0`, `:v9.0` and everything under
`//img/constraints/ppc64le` and `//img/constraints/riscv64` exist but are not listed, so a target
platform declaring one of them has no variant mapping at all. Routing tolerates that - an
architecture whose variants all select the same manifest gets a condition with no variant in it,
which an unlisted variant still matches - but `target_os_cpu` fails on it, loudly.
"""

# Bazel OS constraint value -> GOOS, as used in OCI platform objects.
OS_CONSTRAINTS = {
    "@platforms//os:android": "android",
    "@platforms//os:freebsd": "freebsd",
    "@platforms//os:ios": "ios",
    "@platforms//os:linux": "linux",
    "@platforms//os:macos": "darwin",
    "@platforms//os:netbsd": "netbsd",
    "@platforms//os:openbsd": "openbsd",
    "@platforms//os:wasi": "wasip1",
    "@platforms//os:windows": "windows",
}

# Bazel CPU constraint value -> GOARCH, as used in OCI platform objects.
#
# Canonical constraint values only. `@platforms//cpu:arm64` is an alias of `:aarch64`, so listing
# it alongside its target would generate a pair of identical `config_setting`s. Note that
# `@platforms//cpu:arm` is *not* such an alias: it points at `:aarch32`, a constraint value of its
# own that nothing here maps, so a target platform spelling 32-bit ARM that way has no CPU
# mapping. Only `:armv7` does.
CPU_CONSTRAINTS = {
    "@platforms//cpu:aarch64": "arm64",
    "@platforms//cpu:armv7": "arm",
    "@platforms//cpu:mips64": "mips64",
    "@platforms//cpu:ppc64le": "ppc64le",
    "@platforms//cpu:riscv64": "riscv64",
    "@platforms//cpu:s390x": "s390x",
    "@platforms//cpu:wasm32": "wasm",
    "@platforms//cpu:x86_32": "386",
    "@platforms//cpu:x86_64": "amd64",
}

_AMD64_VARIANTS = {"//img/constraints/amd64:v%d" % i: "v%d" % i for i in range(1, 5)}

_ARM_VARIANTS = {"//img/constraints/arm:v%d" % i: "v%d" % i for i in range(5, 9)}

_ARM64_VARIANTS = {"//img/constraints/arm64:v8.%d" % i: "v8.%d" % i for i in range(1, 10)}

_ARM64_VARIANTS.update({"//img/constraints/arm64:v9": "v9"})

_ARM64_VARIANTS.update({"//img/constraints/arm64:v9.%d" % i: "v9.%d" % i for i in range(1, 8)})

# The variant constraint value denoting a platform that declares no microarchitecture level.
# `//img/constraints:variant` has it as its default value, so every target platform holds either
# this or one of the values below.
EMPTY_VARIANT_CONSTRAINT = "//img/constraints:empty_variant"

# Variant constraint value -> the "variant" field of an OCI platform object, per architecture.
#
# A variant only ever distinguishes manifests of one architecture, so the routing conditions of an
# os/architecture pair are generated from that architecture's variants alone. Mixing in the
# variants of other architectures would leave every one of them unmatched, which defeats the
# collapse in `selection_configs` and turns a plain linux/arm64 condition into nineteen.
VARIANT_CONSTRAINTS_BY_ARCHITECTURE = {
    "amd64": _AMD64_VARIANTS,
    "arm": _ARM_VARIANTS,
    "arm64": _ARM64_VARIANTS,
}

# The same mapping, flattened, as `//img/private/config:target_os_cpu` reads it.
VARIANT_CONSTRAINTS = {EMPTY_VARIANT_CONSTRAINT: ""}

VARIANT_CONSTRAINTS.update(_AMD64_VARIANTS)

VARIANT_CONSTRAINTS.update(_ARM_VARIANTS)

VARIANT_CONSTRAINTS.update(_ARM64_VARIANTS)
