load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "compress",
    srcs = [
        "compress.go",
        "estargz.go",
        "factory.go",
        "options.go",
    ],
    importpath = "github.com/bazel-contrib/rules_img/img_tool/pkg/compress",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/api",
        "@com_github_containerd_stargz_snapshotter_estargz//:estargz",
        "@com_github_containerd_stargz_snapshotter_estargz//zstdchunked",
        "@com_github_klauspost_compress//zstd",
        "@com_github_klauspost_pgzip//:pgzip",
    ],
)

go_test(
    name = "compress_test",
    size = "small",
    srcs = ["cpu_dependent_output_test.go"],
    data = glob(["testdata/**"]),
    embed = [":compress"],
    deps = ["//pkg/api"],
)
