load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_img//img:multi_deploy.bzl", "multi_deploy")
load("@rules_img//img:push.bzl", "image_push")
load(":defs.bzl", "deploy_bundle", "no_deploy_infos")

image_push(
    name = "nginx",
    image = "@nginx//:image",
    # Set the destination registry per-image here, or globally in .bazelrc via
    # --@rules_img//img/settings:destination_registry=docker.acme.tld
    # registry = "docker.acme.tld",
    repository = "malt3/nginx",
    visibility = ["//visibility:public"],
)

multi_deploy(
    name = "multi_deploy",
    operations = [
        ":nginx",
        "//extend:push",
        "//load:load_image",
        "//load:load_image_templated",
        "//load:load_index",
        "//load:load_alpine",
        "//:push_single_layer",
        "//:push_multi_layer",
        "//:push_annotated",
        "//:push_index",
        "//:push_complex",
    ],
)

deploy_bundle(
    name = "bundle",
    operations = [
        "//load:load_image",
        "//:push_single_layer",
    ],
)

# Mixes a MultipleDeployInfo target with plain DeployInfo targets.
multi_deploy(
    name = "bundled_deploy",
    operations = [
        ":nginx",
        ":bundle",
        "//load:load_index",
    ],
)

deploy_bundle(
    name = "empty_bundle",
    operations = [],
)

no_deploy_infos(name = "unset_bundle")

# MultipleDeployInfo is allowed to be empty and results in a no-op.
multi_deploy(
    name = "empty_deploy",
    operations = [
        ":empty_bundle",
        ":unset_bundle",
    ],
)

build_test(
    name = "test",
    targets = [
        ":bundled_deploy",
        ":multi_deploy",
    ],
)

build_test(
    name = "empty_test",
    targets = [":empty_deploy"],
)
