load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

filegroup(
    name = "all_files",
    srcs = glob(["**"]),
    visibility = ["//img/private/release:__subpackages__"],
)

bzl_library(
    name = "pull",
    srcs = ["pull.bzl"],
    visibility = ["//img:__subpackages__"],
    deps = [
        ":download",
        ":registry",
        "//img/private:manifest_media_type",
        "//img/private/platforms",
        "//img/private/platforms:constraints",
        "//img/private/platforms:matching",
        "@bazel_skylib//lib:sets",
        "@img_toolchain//:defs",
    ],
)

bzl_library(
    name = "pull_blob",
    srcs = ["pull_blob.bzl"],
    visibility = ["//img:__subpackages__"],
    deps = [
        ":download",
        "@img_toolchain//:defs",
    ],
)

bzl_library(
    name = "download",
    srcs = ["download.bzl"],
    visibility = ["//img:__subpackages__"],
    deps = [
        ":registry",
        "@img_toolchain//:defs",
    ],
)

bzl_library(
    name = "image_repo",
    srcs = ["image_repo.bzl"],
    visibility = ["//img:__subpackages__"],
    deps = [
        ":repo_names",
        "//img/private/platforms",
        "//img/private/platforms:matching",
    ],
)

bzl_library(
    name = "repo_names",
    srcs = ["repo_names.bzl"],
    visibility = ["//img:__subpackages__"],
)

bzl_library(
    name = "registry",
    srcs = ["registry.bzl"],
    visibility = ["//img:__subpackages__"],
)

bzl_library(
    name = "toolchains_repo",
    srcs = ["toolchains_repo.bzl"],
    visibility = ["//img:__subpackages__"],
)
