"""Repository rule for creating image repos from pulled blobs."""

load("//img/private/platforms:selection.bzl", "render_image_alias", "render_unconditional_image_alias", "selection_configs")
load(":package_metadata.bzl", "PACKAGE_METADATA_LOAD", "REPO_FILE", "image_purl", "package_metadata_target")

_BUILD_HEADER = (
    "# This file was generated by the images module extension.\n" +
    PACKAGE_METADATA_LOAD +
    'load("@rules_img//img/private:import.bzl", "image_import")\n'
)

_IMPORT = """
image_import(
    name = {name},
    digest = {digest},
    descriptor = {descriptor},
    data = {data},
    files = {files},
    registries = {registries},
    repository = {repository},
    tag = {tag},
    visibility = ["//visibility:public"],
)
"""

def _read_blob(rctx, digest):
    if digest not in rctx.attr.files:
        fail("Digest {} not found in files.".format(digest))
    return rctx.read(rctx.path(rctx.attr.files[digest]))

def _purl(rctx):
    return image_purl(
        rctx.attr.repository,
        rctx.attr.digest or rctx.attr.tag,
        json.decode(rctx.attr.registries),
    )

def _files_attr(files):
    entries = [
        "        {}: \"{}\",".format(repr(digest), str(label))
        for (digest, label) in files.items()
    ]
    return "{\n" + "\n".join(entries) + "\n    }"

def _read_image(rctx):
    """Read the blobs this repository imports.

    Returns:
        A tuple of the digest -> blob contents dict, whether the root blob is an index, and the
        platform a single-platform image declares in its config (None if it declares none).
    """
    root_digest = rctx.attr.digest
    data = {root_digest: _read_blob(rctx, root_digest)}
    root_content = json.decode(data[root_digest])

    if "manifests" in root_content:
        # An index: read every child manifest and its config, so the import can describe all of
        # them. Only the repository holding a multi-platform image unmodified does this; the
        # repositories a build reaches through `image()` hold a single child manifest each.
        for child_manifest in root_content.get("manifests", []):
            child_digest = child_manifest.get("digest")
            if not child_digest:
                continue
            data[child_digest] = _read_blob(rctx, child_digest)
            child_config_digest = json.decode(data[child_digest]).get("config", {}).get("digest")
            if child_config_digest:
                data[child_config_digest] = _read_blob(rctx, child_config_digest)
        return (data, True, None)

    config_digest = root_content.get("config", {}).get("digest")
    if not config_digest:
        return (data, False, None)
    data[config_digest] = _read_blob(rctx, config_digest)
    config = json.decode(data[config_digest])
    os = config.get("os", "")
    architecture = config.get("architecture", "")
    if not os or not architecture:
        return (data, False, None)
    return (data, False, {
        "os": os,
        "architecture": architecture,
        "variant": config.get("variant", ""),
    })

def _image_repo_impl(rctx):
    """Create an image repository from pulled blob repositories."""
    (data, is_index, platform) = _read_image(rctx)

    import_attrs = dict(
        digest = repr(rctx.attr.digest),
        descriptor = repr(rctx.attr.descriptor),
        data = json.encode(data),
        files = _files_attr(rctx.attr.files),
        registries = rctx.attr.registries,
        repository = repr(rctx.attr.repository),
        tag = repr(rctx.attr.tag) if rctx.attr.tag else "None",
    )
    content = _BUILD_HEADER + package_metadata_target(_purl(rctx))

    if not rctx.attr.select_platform:
        # A manifest the routing selects between, or a whole index behind `:original`. Which
        # target platforms it is compatible with is decided by the repository referring to it,
        # so it carries no constraint that could contradict that decision.
        content += _IMPORT.format(name = repr("image"), **import_attrs)
    elif is_index:
        fail("select_platform is only supported for single-platform images, but {} is an index.".format(rctx.attr.digest))
    else:
        content += _IMPORT.format(name = repr("original"), **import_attrs)
        if platform == None or not selection_configs([platform]):
            # Either the config names no platform, or it names one no Bazel constraint value
            # describes - a GOOS or GOARCH outside `//img/private/platforms:tables.bzl`, or a
            # variant no manifest of that architecture could have. Constraining `:image` on a
            # platform that cannot be expressed would make it incompatible everywhere, including
            # on the platform the image is actually for, so it stays unconstrained as it was
            # before the routing existed.
            content += render_unconditional_image_alias(":original")
        else:
            content += render_image_alias([platform], [":original"])

    rctx.file("BUILD.bazel", content = content)
    rctx.file("REPO.bazel", REPO_FILE)

image_repo = repository_rule(
    implementation = _image_repo_impl,
    doc = """Creates an image repository from pulled blobs.

This repository rule is used by the images module extension to create
image repositories that reference blob repositories for manifests, configs,
and layers.

It imports exactly the blobs listed in `files`, so what a build has to fetch is decided by what
the extension puts there. A multi-platform image is spread over several of these repositories -
one per child manifest of the index, plus one holding the index with all of its children - and
an `image_router` picks between them.""",
    attrs = {
        "digest": attr.string(
            mandatory = True,
            doc = "The root digest (manifest or index) of the image.",
        ),
        "descriptor": attr.string(
            doc = """The index descriptor referring to this manifest, encoded as JSON.

Set when the repository imports one child manifest of a pulled index. The descriptor carries
what only the index knows about the manifest: its platform, its annotations, and its media type,
which a manifest that omits its own `mediaType` field does not carry.""",
        ),
        "files": attr.string_keyed_label_dict(
            mandatory = True,
            doc = """Dict of digest -> label for blob files.

Only the blobs this repository imports. Labels of a repository rule are fetched eagerly, so
listing the blobs of other platforms here would defeat per-platform fetching.""",
        ),
        "registries": attr.string(
            mandatory = True,
            doc = "JSON-encoded list of registries.",
        ),
        "repository": attr.string(
            mandatory = True,
            doc = "The image repository name.",
        ),
        "select_platform": attr.bool(
            default = False,
            doc = """Whether this repository is the entry point of a single-platform image.

Such an image needs no routing repository of its own: the import is exposed as `:original`, and
`:image` is a `select()` in front of it that is incompatible with target platforms the image's
config does not describe.""",
        ),
        "tag": attr.string(
            doc = "The image tag (optional).",
        ),
    },
)
