"""The repository a pulled multi-platform image is referred to through."""

load("//img/private/platforms:selection.bzl", "render_image_alias")
load(":package_metadata.bzl", "PACKAGE_METADATA_LOAD", "REPO_FILE", "image_purl", "package_metadata_target")

_BUILD_HEADER = """# This file was generated by the images module extension.
# Routing for {reference}.
#
# Choosing a manifest here, rather than importing the whole index and picking one during
# analysis, is what makes a pulled multi-platform image lazy: only the repository of the
# selected manifest is ever fetched, along with its config and its layers.
"""

_ORIGINAL_ALIAS = """
alias(
    name = "original",
    actual = {original},
    visibility = ["//visibility:public"],
)
"""

def _image_router_impl(rctx):
    platforms = json.decode(rctx.attr.platforms)

    # The purl of the image as it was pulled. This repository is the one a user names, so it is
    # the one that has to record the digest they pinned; the child repositories record the
    # manifest each of them holds.
    purl = image_purl(rctx.attr.repository, rctx.attr.digest, json.decode(rctx.attr.registries))
    rctx.file("BUILD.bazel", content = (
        _BUILD_HEADER.format(reference = "{}@{}".format(rctx.attr.repository, rctx.attr.digest)) +
        PACKAGE_METADATA_LOAD +
        package_metadata_target(purl) +
        render_image_alias(platforms, rctx.attr.children) +
        _ORIGINAL_ALIAS.format(original = repr(rctx.attr.original))
    ))
    rctx.file("REPO.bazel", REPO_FILE)

image_router = repository_rule(
    implementation = _image_router_impl,
    doc = """Creates the repository a pulled multi-platform image is referred to through.

It holds no blobs and has no label attributes: the labels it routes to are written into the
generated BUILD file as plain strings. Fetching this repository therefore fetches nothing else,
and loading `:image` reaches only the manifest selected for the target platform.""",
    attrs = {
        "digest": attr.string(
            mandatory = True,
            doc = "Digest of the image index, as pulled. Recorded in the package metadata.",
        ),
        "repository": attr.string(
            mandatory = True,
            doc = "The image repository name. Recorded in the package metadata.",
        ),
        "registries": attr.string(
            mandatory = True,
            doc = "JSON-encoded list of registries. Recorded in the package metadata.",
        ),
        "platforms": attr.string(
            mandatory = True,
            doc = """JSON list of the platform of every child of the index, in index order.

An entry may be null for a child whose platform is unknown; it is never selected.""",
        ),
        "children": attr.string_list(
            mandatory = True,
            doc = """Label of the target importing every child of the index, in index order.

Deliberately strings rather than labels: a label attribute would make Bazel fetch the repository
of every child as soon as this repository is fetched.""",
        ),
        "original": attr.string(
            mandatory = True,
            doc = "Label of the target importing the index unmodified, exposed as `:original`.",
        ),
    },
)
