// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/proto/baselayer/baselayer.proto

package baselayer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED  EntryType = 0
	EntryType_ENTRY_TYPE_REGULAR      EntryType = 1
	EntryType_ENTRY_TYPE_DIRECTORY    EntryType = 2
	EntryType_ENTRY_TYPE_SYMLINK      EntryType = 3
	EntryType_ENTRY_TYPE_HARDLINK     EntryType = 4
	EntryType_ENTRY_TYPE_CHAR_DEVICE  EntryType = 5
	EntryType_ENTRY_TYPE_BLOCK_DEVICE EntryType = 6
	EntryType_ENTRY_TYPE_FIFO         EntryType = 7
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_REGULAR",
		2: "ENTRY_TYPE_DIRECTORY",
		3: "ENTRY_TYPE_SYMLINK",
		4: "ENTRY_TYPE_HARDLINK",
		5: "ENTRY_TYPE_CHAR_DEVICE",
		6: "ENTRY_TYPE_BLOCK_DEVICE",
		7: "ENTRY_TYPE_FIFO",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED":  0,
		"ENTRY_TYPE_REGULAR":      1,
		"ENTRY_TYPE_DIRECTORY":    2,
		"ENTRY_TYPE_SYMLINK":      3,
		"ENTRY_TYPE_HARDLINK":     4,
		"ENTRY_TYPE_CHAR_DEVICE":  5,
		"ENTRY_TYPE_BLOCK_DEVICE": 6,
		"ENTRY_TYPE_FIFO":         7,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_baselayer_baselayer_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_pkg_proto_baselayer_baselayer_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_baselayer_baselayer_proto_rawDescGZIP(), []int{0}
}

type BaseEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type           EntryType              `protobuf:"varint,2,opt,name=type,proto3,enum=pkg.proto.baselayer.EntryType" json:"type,omitempty"`
	Mode           int64                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid            int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid            int64                  `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	Uname          string                 `protobuf:"bytes,6,opt,name=uname,proto3" json:"uname,omitempty"`
	Gname          string                 `protobuf:"bytes,7,opt,name=gname,proto3" json:"gname,omitempty"`
	Linkname       string                 `protobuf:"bytes,8,opt,name=linkname,proto3" json:"linkname,omitempty"`
	Devmajor       int64                  `protobuf:"varint,9,opt,name=devmajor,proto3" json:"devmajor,omitempty"`
	Devminor       int64                  `protobuf:"varint,10,opt,name=devminor,proto3" json:"devminor,omitempty"`
	MtimeUnixNanos int64                  `protobuf:"varint,11,opt,name=mtime_unix_nanos,json=mtimeUnixNanos,proto3" json:"mtime_unix_nanos,omitempty"`
	AtimeUnixNanos int64                  `protobuf:"varint,12,opt,name=atime_unix_nanos,json=atimeUnixNanos,proto3" json:"atime_unix_nanos,omitempty"`
	CtimeUnixNanos int64                  `protobuf:"varint,13,opt,name=ctime_unix_nanos,json=ctimeUnixNanos,proto3" json:"ctime_unix_nanos,omitempty"`
	PaxRecords     map[string]string      `protobuf:"bytes,14,rep,name=pax_records,json=paxRecords,proto3" json:"pax_records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Xattrs         map[string]string      `protobuf:"bytes,15,rep,name=xattrs,proto3" json:"xattrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Content:
	//
	//	*BaseEntry_FilePath
	//	*BaseEntry_Inline
	Content       isBaseEntry_Content `protobuf_oneof:"content"`
	Producer      string              `protobuf:"bytes,18,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseEntry) Reset() {
	*x = BaseEntry{}
	mi := &file_pkg_proto_baselayer_baselayer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEntry) ProtoMessage() {}

func (x *BaseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_baselayer_baselayer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEntry.ProtoReflect.Descriptor instead.
func (*BaseEntry) Descriptor() ([]byte, []int) {
	return file_pkg_proto_baselayer_baselayer_proto_rawDescGZIP(), []int{0}
}

func (x *BaseEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BaseEntry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *BaseEntry) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *BaseEntry) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BaseEntry) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *BaseEntry) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *BaseEntry) GetGname() string {
	if x != nil {
		return x.Gname
	}
	return ""
}

func (x *BaseEntry) GetLinkname() string {
	if x != nil {
		return x.Linkname
	}
	return ""
}

func (x *BaseEntry) GetDevmajor() int64 {
	if x != nil {
		return x.Devmajor
	}
	return 0
}

func (x *BaseEntry) GetDevminor() int64 {
	if x != nil {
		return x.Devminor
	}
	return 0
}

func (x *BaseEntry) GetMtimeUnixNanos() int64 {
	if x != nil {
		return x.MtimeUnixNanos
	}
	return 0
}

func (x *BaseEntry) GetAtimeUnixNanos() int64 {
	if x != nil {
		return x.AtimeUnixNanos
	}
	return 0
}

func (x *BaseEntry) GetCtimeUnixNanos() int64 {
	if x != nil {
		return x.CtimeUnixNanos
	}
	return 0
}

func (x *BaseEntry) GetPaxRecords() map[string]string {
	if x != nil {
		return x.PaxRecords
	}
	return nil
}

func (x *BaseEntry) GetXattrs() map[string]string {
	if x != nil {
		return x.Xattrs
	}
	return nil
}

func (x *BaseEntry) GetContent() isBaseEntry_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *BaseEntry) GetFilePath() string {
	if x != nil {
		if x, ok := x.Content.(*BaseEntry_FilePath); ok {
			return x.FilePath
		}
	}
	return ""
}

func (x *BaseEntry) GetInline() []byte {
	if x != nil {
		if x, ok := x.Content.(*BaseEntry_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

func (x *BaseEntry) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

type isBaseEntry_Content interface {
	isBaseEntry_Content()
}

type BaseEntry_FilePath struct {
	FilePath string `protobuf:"bytes,16,opt,name=file_path,json=filePath,proto3,oneof"`
}

type BaseEntry_Inline struct {
	Inline []byte `protobuf:"bytes,17,opt,name=inline,proto3,oneof"`
}

func (*BaseEntry_FilePath) isBaseEntry_Content() {}

func (*BaseEntry_Inline) isBaseEntry_Content() {}

var File_pkg_proto_baselayer_baselayer_proto protoreflect.FileDescriptor

const file_pkg_proto_baselayer_baselayer_proto_rawDesc = "" +
	"\n" +
	"#pkg/proto/baselayer/baselayer.proto\x12\x13pkg.proto.baselayer\"\xf8\x05\n" +
	"\tBaseEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.pkg.proto.baselayer.EntryTypeR\x04type\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x03R\x04mode\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\x03R\x03gid\x12\x14\n" +
	"\x05uname\x18\x06 \x01(\tR\x05uname\x12\x14\n" +
	"\x05gname\x18\a \x01(\tR\x05gname\x12\x1a\n" +
	"\blinkname\x18\b \x01(\tR\blinkname\x12\x1a\n" +
	"\bdevmajor\x18\t \x01(\x03R\bdevmajor\x12\x1a\n" +
	"\bdevminor\x18\n" +
	" \x01(\x03R\bdevminor\x12(\n" +
	"\x10mtime_unix_nanos\x18\v \x01(\x03R\x0emtimeUnixNanos\x12(\n" +
	"\x10atime_unix_nanos\x18\f \x01(\x03R\x0eatimeUnixNanos\x12(\n" +
	"\x10ctime_unix_nanos\x18\r \x01(\x03R\x0ectimeUnixNanos\x12O\n" +
	"\vpax_records\x18\x0e \x03(\v2..pkg.proto.baselayer.BaseEntry.PaxRecordsEntryR\n" +
	"paxRecords\x12B\n" +
	"\x06xattrs\x18\x0f \x03(\v2*.pkg.proto.baselayer.BaseEntry.XattrsEntryR\x06xattrs\x12\x1d\n" +
	"\tfile_path\x18\x10 \x01(\tH\x00R\bfilePath\x12\x18\n" +
	"\x06inline\x18\x11 \x01(\fH\x00R\x06inline\x12\x1a\n" +
	"\bproducer\x18\x12 \x01(\tR\bproducer\x1a=\n" +
	"\x0fPaxRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vXattrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\acontent*\xd8\x01\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENTRY_TYPE_REGULAR\x10\x01\x12\x18\n" +
	"\x14ENTRY_TYPE_DIRECTORY\x10\x02\x12\x16\n" +
	"\x12ENTRY_TYPE_SYMLINK\x10\x03\x12\x17\n" +
	"\x13ENTRY_TYPE_HARDLINK\x10\x04\x12\x1a\n" +
	"\x16ENTRY_TYPE_CHAR_DEVICE\x10\x05\x12\x1b\n" +
	"\x17ENTRY_TYPE_BLOCK_DEVICE\x10\x06\x12\x13\n" +
	"\x0fENTRY_TYPE_FIFO\x10\aBKZIgithub.com/bazel-contrib/rules_img/img_tool/pkg/proto/baselayer;baselayerb\x06proto3"

var (
	file_pkg_proto_baselayer_baselayer_proto_rawDescOnce sync.Once
	file_pkg_proto_baselayer_baselayer_proto_rawDescData []byte
)

func file_pkg_proto_baselayer_baselayer_proto_rawDescGZIP() []byte {
	file_pkg_proto_baselayer_baselayer_proto_rawDescOnce.Do(func() {
		file_pkg_proto_baselayer_baselayer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_baselayer_baselayer_proto_rawDesc), len(file_pkg_proto_baselayer_baselayer_proto_rawDesc)))
	})
	return file_pkg_proto_baselayer_baselayer_proto_rawDescData
}

var file_pkg_proto_baselayer_baselayer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_baselayer_baselayer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_baselayer_baselayer_proto_goTypes = []any{
	(EntryType)(0),    // 0: pkg.proto.baselayer.EntryType
	(*BaseEntry)(nil), // 1: pkg.proto.baselayer.BaseEntry
	nil,               // 2: pkg.proto.baselayer.BaseEntry.PaxRecordsEntry
	nil,               // 3: pkg.proto.baselayer.BaseEntry.XattrsEntry
}
var file_pkg_proto_baselayer_baselayer_proto_depIdxs = []int32{
	0, // 0: pkg.proto.baselayer.BaseEntry.type:type_name -> pkg.proto.baselayer.EntryType
	2, // 1: pkg.proto.baselayer.BaseEntry.pax_records:type_name -> pkg.proto.baselayer.BaseEntry.PaxRecordsEntry
	3, // 2: pkg.proto.baselayer.BaseEntry.xattrs:type_name -> pkg.proto.baselayer.BaseEntry.XattrsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_baselayer_baselayer_proto_init() }
func file_pkg_proto_baselayer_baselayer_proto_init() {
	if File_pkg_proto_baselayer_baselayer_proto != nil {
		return
	}
	file_pkg_proto_baselayer_baselayer_proto_msgTypes[0].OneofWrappers = []any{
		(*BaseEntry_FilePath)(nil),
		(*BaseEntry_Inline)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_baselayer_baselayer_proto_rawDesc), len(file_pkg_proto_baselayer_baselayer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_baselayer_baselayer_proto_goTypes,
		DependencyIndexes: file_pkg_proto_baselayer_baselayer_proto_depIdxs,
		EnumInfos:         file_pkg_proto_baselayer_baselayer_proto_enumTypes,
		MessageInfos:      file_pkg_proto_baselayer_baselayer_proto_msgTypes,
	}.Build()
	File_pkg_proto_baselayer_baselayer_proto = out.File
	file_pkg_proto_baselayer_baselayer_proto_goTypes = nil
	file_pkg_proto_baselayer_baselayer_proto_depIdxs = nil
}
