name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Every day at 10:09 UTC.
    - cron: '9 10 * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  buildifier_check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8 # 0.15.0
      with:
        bazelrc: import %workspace%/.github/workflows/ci.bazelrc
    - name: Run buildifier
      run: bazelisk run //util:buildifier.check
  tidy_and_test_matrix:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-13, macos-15, ubuntu-22.04, windows-2025]
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8 # 0.15.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}-${{ matrix.runner }}-tidy_and_test_matrix
        repository-cache: true
        bazelrc: import %workspace%/.github/workflows/ci.bazelrc
    - name: Execute Tests
      run: bazelisk test //... @rules_img_tool//...
  integration_test_matrix:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-13, macos-15, ubuntu-22.04, windows-2025]
    runs-on: ${{ matrix.runner }}
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8 # 0.15.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}-${{ matrix.runner }}-integration_test_matrix
        repository-cache: true
        bazelrc: import %workspace%/.github/workflows/ci.bazelrc
    - name: Execute Integration Tests
      run: bazelisk test "//e2e:integration_tests"

  all_ci_tests:
    runs-on: ubuntu-22.04
    needs: [tidy_and_test_matrix, integration_test_matrix]
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
